// Code generated by go-swagger; DO NOT EDIT.

// Package restapi maxon back
//
//	Makson zon zon
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: development
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
