// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Makson zon zon",
    "title": "maxon back",
    "version": "development"
  },
  "paths": {
    "/bind_user_wallet/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Bind User Wallet",
        "operationId": "BindUserWallet",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Wallet body",
            "name": "WalletBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/WalletBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Bind Wallet Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/collect_referral_earn/{tg_id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Collect Referral Earn",
        "operationId": "CollectReferralEarn",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Referral Balance Response",
            "schema": {
              "$ref": "#/definitions/ReferralBalance"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/create_referral_user/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create Referral User",
        "operationId": "CreateReferralUser",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Referral Link Body",
            "name": "ReferralLink",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReferralLink"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Referral Link Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/get_referral_link/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Get Referral Link",
        "operationId": "GetReferralLink",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Referral Link Response",
            "schema": {
              "$ref": "#/definitions/ReferralLink"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/get_user/{tg_id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get User Progress",
        "operationId": "GetUserProgress",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get User Progress Response",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/get_user_cards/{tg_id}": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "Get User Cards",
        "operationId": "GetUserCards",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get User Cards Response",
            "schema": {
              "$ref": "#/definitions/CardsBody"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/near_transaction": {
      "post": {
        "tags": [
          "Near"
        ],
        "summary": "Transit Near",
        "operationId": "TransitNear",
        "parameters": [
          {
            "description": "Get Near",
            "name": "GetNearBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GetNearBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Transit Near Response",
            "schema": {
              "$ref": "#/definitions/NearTransit"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/save_progress/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Save Progress",
        "operationId": "SaveProgress",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Tap Token Body",
            "name": "TapTokenBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TapTokenBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Start Auto Clicker",
        "operationId": "StartAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Start Energy Offline",
        "operationId": "StartEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Start Energy Collect Body",
            "name": "StartEnergyCollectBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/StartEnergyCollectBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Start Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Stop Auto Clicker",
        "operationId": "StopAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Stop Energy Offline",
        "operationId": "StopEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Stop Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/update_user_card/{tg_id}": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "Update User Card",
        "operationId": "UpdateUserCard",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Card Update Body",
            "name": "CardUpdateBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CardUpdateBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update Card Response",
            "schema": {
              "$ref": "#/definitions/CardBody"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CardBody": {
      "type": "object",
      "properties": {
        "auto_clicker": {
          "type": "boolean"
        },
        "card_id": {
          "type": "integer"
        },
        "card_name": {
          "type": "string"
        },
        "created_at": {
          "type": "integer"
        },
        "current_level": {
          "type": "integer"
        },
        "updated_at": {
          "type": "integer"
        },
        "user_id": {
          "type": "integer"
        }
      }
    },
    "CardUpdateBody": {
      "type": "object",
      "properties": {
        "card_name": {
          "type": "string",
          "enum": [
            "power_click",
            "auto_clicker",
            "energy_booster"
          ]
        }
      }
    },
    "CardsBody": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "user_cards": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CardBody"
          }
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetNearBody": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "receiving_wallet": {
          "type": "string"
        },
        "token_contract": {
          "type": "string"
        }
      }
    },
    "NearTransit": {
      "type": "object",
      "properties": {
        "result": {
          "type": "string"
        }
      }
    },
    "ReferralBalance": {
      "type": "object",
      "required": [
        "referral_balance"
      ],
      "properties": {
        "referral_balance": {
          "type": "integer"
        }
      }
    },
    "ReferralLink": {
      "type": "object",
      "required": [
        "referral_link"
      ],
      "properties": {
        "referral_link": {
          "type": "string"
        }
      }
    },
    "StartEnergyCollectBody": {
      "type": "object",
      "required": [
        "current_energy_token"
      ],
      "properties": {
        "current_energy_token": {
          "type": "string"
        }
      }
    },
    "TapTokenBody": {
      "type": "object",
      "required": [
        "tap_token"
      ],
      "properties": {
        "tap_token": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "tg_id",
        "balance",
        "wallet",
        "username",
        "energy"
      ],
      "properties": {
        "balance": {
          "type": "integer"
        },
        "energy": {
          "type": "integer"
        },
        "referral_balance": {
          "type": "integer"
        },
        "tg_id": {
          "type": "integer"
        },
        "upgrade_level": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        },
        "wallet": {
          "type": "string"
        }
      }
    },
    "WalletBody": {
      "type": "object",
      "required": [
        "wallet"
      ],
      "properties": {
        "wallet": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Makson zon zon",
    "title": "maxon back",
    "version": "development"
  },
  "paths": {
    "/bind_user_wallet/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Bind User Wallet",
        "operationId": "BindUserWallet",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Wallet body",
            "name": "WalletBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/WalletBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Bind Wallet Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/collect_referral_earn/{tg_id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Collect Referral Earn",
        "operationId": "CollectReferralEarn",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Referral Balance Response",
            "schema": {
              "$ref": "#/definitions/ReferralBalance"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/create_referral_user/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create Referral User",
        "operationId": "CreateReferralUser",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Referral Link Body",
            "name": "ReferralLink",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReferralLink"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Referral Link Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/get_referral_link/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Get Referral Link",
        "operationId": "GetReferralLink",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Referral Link Response",
            "schema": {
              "$ref": "#/definitions/ReferralLink"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/get_user/{tg_id}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get User Progress",
        "operationId": "GetUserProgress",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get User Progress Response",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/get_user_cards/{tg_id}": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "Get User Cards",
        "operationId": "GetUserCards",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get User Cards Response",
            "schema": {
              "$ref": "#/definitions/CardsBody"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/near_transaction": {
      "post": {
        "tags": [
          "Near"
        ],
        "summary": "Transit Near",
        "operationId": "TransitNear",
        "parameters": [
          {
            "description": "Get Near",
            "name": "GetNearBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GetNearBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Transit Near Response",
            "schema": {
              "$ref": "#/definitions/NearTransit"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/save_progress/{tg_id}": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Save Progress",
        "operationId": "SaveProgress",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Tap Token Body",
            "name": "TapTokenBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/TapTokenBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Start Auto Clicker",
        "operationId": "StartAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Start Energy Offline",
        "operationId": "StartEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Start Energy Collect Body",
            "name": "StartEnergyCollectBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/StartEnergyCollectBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Start Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Stop Auto Clicker",
        "operationId": "StopAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Stop Energy Offline",
        "operationId": "StopEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Stop Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/update_user_card/{tg_id}": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "Update User Card",
        "operationId": "UpdateUserCard",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Card Update Body",
            "name": "CardUpdateBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CardUpdateBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update Card Response",
            "schema": {
              "$ref": "#/definitions/CardBody"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CardBody": {
      "type": "object",
      "properties": {
        "auto_clicker": {
          "type": "boolean"
        },
        "card_id": {
          "type": "integer"
        },
        "card_name": {
          "type": "string"
        },
        "created_at": {
          "type": "integer"
        },
        "current_level": {
          "type": "integer"
        },
        "updated_at": {
          "type": "integer"
        },
        "user_id": {
          "type": "integer"
        }
      }
    },
    "CardUpdateBody": {
      "type": "object",
      "properties": {
        "card_name": {
          "type": "string",
          "enum": [
            "power_click",
            "auto_clicker",
            "energy_booster"
          ]
        }
      }
    },
    "CardsBody": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "user_cards": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CardBody"
          }
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetNearBody": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "receiving_wallet": {
          "type": "string"
        },
        "token_contract": {
          "type": "string"
        }
      }
    },
    "NearTransit": {
      "type": "object",
      "properties": {
        "result": {
          "type": "string"
        }
      }
    },
    "ReferralBalance": {
      "type": "object",
      "required": [
        "referral_balance"
      ],
      "properties": {
        "referral_balance": {
          "type": "integer"
        }
      }
    },
    "ReferralLink": {
      "type": "object",
      "required": [
        "referral_link"
      ],
      "properties": {
        "referral_link": {
          "type": "string"
        }
      }
    },
    "StartEnergyCollectBody": {
      "type": "object",
      "required": [
        "current_energy_token"
      ],
      "properties": {
        "current_energy_token": {
          "type": "string"
        }
      }
    },
    "TapTokenBody": {
      "type": "object",
      "required": [
        "tap_token"
      ],
      "properties": {
        "tap_token": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "tg_id",
        "balance",
        "wallet",
        "username",
        "energy"
      ],
      "properties": {
        "balance": {
          "type": "integer"
        },
        "energy": {
          "type": "integer"
        },
        "referral_balance": {
          "type": "integer"
        },
        "tg_id": {
          "type": "integer"
        },
        "upgrade_level": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        },
        "wallet": {
          "type": "string"
        }
      }
    },
    "WalletBody": {
      "type": "object",
      "required": [
        "wallet"
      ],
      "properties": {
        "wallet": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
