// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Makson zon zon",
    "title": "maxon back",
    "version": "development"
  },
  "paths": {
    "/get_user_progress/{tg_id}": {
      "get": {
        "tags": [
          "Progress"
        ],
        "summary": "Get User Progress",
        "operationId": "GetUserProgress",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get User Progress Response",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/near_transaction": {
      "post": {
        "tags": [
          "Near"
        ],
        "summary": "Transit Near",
        "operationId": "TransitNear",
        "parameters": [
          {
            "description": "Get Near",
            "name": "GetNearBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GetNearBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Transit Near Response",
            "schema": {
              "$ref": "#/definitions/NearTransit"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/save_progress": {
      "post": {
        "tags": [
          "Progress"
        ],
        "summary": "Save Progress",
        "operationId": "SaveProgress",
        "parameters": [
          {
            "description": "Save progress body",
            "name": "Progress",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Progress"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Start Auto Clicker",
        "operationId": "StartAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Start Energy Offline",
        "operationId": "StartEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Start Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Stop Auto Clicker",
        "operationId": "StopAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Stop Energy Offline",
        "operationId": "StopEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Stop Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetNearBody": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "receiving_wallet": {
          "type": "string"
        },
        "token_contract": {
          "type": "string"
        }
      }
    },
    "NearTransit": {
      "type": "object",
      "properties": {
        "result": {
          "type": "string"
        }
      }
    },
    "Progress": {
      "type": "object",
      "required": [
        "tg_id",
        "click_count",
        "upgrade_level",
        "upgrade_energy",
        "has_auto_clicker"
      ],
      "properties": {
        "click_count": {
          "type": "integer"
        },
        "has_auto_clicker": {
          "type": "boolean"
        },
        "tg_id": {
          "type": "integer"
        },
        "upgrade_energy": {
          "type": "integer"
        },
        "upgrade_level": {
          "type": "integer"
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "tg_id",
        "click_count",
        "upgrade_level",
        "upgrade_energy",
        "has_auto_clicker"
      ],
      "properties": {
        "click_count": {
          "type": "integer"
        },
        "has_auto_clicker": {
          "type": "boolean"
        },
        "tg_id": {
          "type": "integer"
        },
        "upgrade_energy": {
          "type": "integer"
        },
        "upgrade_level": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Makson zon zon",
    "title": "maxon back",
    "version": "development"
  },
  "paths": {
    "/get_user_progress/{tg_id}": {
      "get": {
        "tags": [
          "Progress"
        ],
        "summary": "Get User Progress",
        "operationId": "GetUserProgress",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get User Progress Response",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/near_transaction": {
      "post": {
        "tags": [
          "Near"
        ],
        "summary": "Transit Near",
        "operationId": "TransitNear",
        "parameters": [
          {
            "description": "Get Near",
            "name": "GetNearBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GetNearBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Transit Near Response",
            "schema": {
              "$ref": "#/definitions/NearTransit"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/save_progress": {
      "post": {
        "tags": [
          "Progress"
        ],
        "summary": "Save Progress",
        "operationId": "SaveProgress",
        "parameters": [
          {
            "description": "Save progress body",
            "name": "Progress",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Progress"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Start Auto Clicker",
        "operationId": "StartAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/start_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Start Energy Offline",
        "operationId": "StartEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Start Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_auto_clicker/{tg_id}": {
      "post": {
        "tags": [
          "AutoClicker"
        ],
        "summary": "Stop Auto Clicker",
        "operationId": "StopAutoClicker",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/stop_energy_collect/{tg_id}": {
      "post": {
        "tags": [
          "Energy"
        ],
        "summary": "Stop Energy Offline",
        "operationId": "StopEnergyOffline",
        "parameters": [
          {
            "type": "integer",
            "description": "The tg ID of user",
            "name": "tg_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Stop Collect Energy Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetNearBody": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "receiving_wallet": {
          "type": "string"
        },
        "token_contract": {
          "type": "string"
        }
      }
    },
    "NearTransit": {
      "type": "object",
      "properties": {
        "result": {
          "type": "string"
        }
      }
    },
    "Progress": {
      "type": "object",
      "required": [
        "tg_id",
        "click_count",
        "upgrade_level",
        "upgrade_energy",
        "has_auto_clicker"
      ],
      "properties": {
        "click_count": {
          "type": "integer"
        },
        "has_auto_clicker": {
          "type": "boolean"
        },
        "tg_id": {
          "type": "integer"
        },
        "upgrade_energy": {
          "type": "integer"
        },
        "upgrade_level": {
          "type": "integer"
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "tg_id",
        "click_count",
        "upgrade_level",
        "upgrade_energy",
        "has_auto_clicker"
      ],
      "properties": {
        "click_count": {
          "type": "integer"
        },
        "has_auto_clicker": {
          "type": "boolean"
        },
        "tg_id": {
          "type": "integer"
        },
        "upgrade_energy": {
          "type": "integer"
        },
        "upgrade_level": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
