// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Makson zon zon",
    "title": "maxon back",
    "version": "development"
  },
  "paths": {
    "/save_progress": {
      "post": {
        "tags": [
          "Progress"
        ],
        "summary": "Save Progress",
        "operationId": "SaveProgress",
        "parameters": [
          {
            "description": "Save progress body",
            "name": "Progress",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Progress"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Progress": {
      "type": "object",
      "required": [
        "coin_number",
        "click_booster",
        "auto_clicker"
      ],
      "properties": {
        "auto_clicker": {
          "type": "boolean"
        },
        "click_booster": {
          "type": "integer"
        },
        "coin_number": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Makson zon zon",
    "title": "maxon back",
    "version": "development"
  },
  "paths": {
    "/save_progress": {
      "post": {
        "tags": [
          "Progress"
        ],
        "summary": "Save Progress",
        "operationId": "SaveProgress",
        "parameters": [
          {
            "description": "Save progress body",
            "name": "Progress",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Progress"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Save Progress Response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Progress": {
      "type": "object",
      "required": [
        "coin_number",
        "click_booster",
        "auto_clicker"
      ],
      "properties": {
        "auto_clicker": {
          "type": "boolean"
        },
        "click_booster": {
          "type": "integer"
        },
        "coin_number": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
