#version: '3.9'

services:
  mini-app-dev:
    container_name: mini-app-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: cmd/mini-app/Dockerfile
    ports:
      - 8205:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5449:5432
    environment:
      POSTGRES_USER: pasha
      POSTGRES_DB: mini_app_db
      POSTGRES_PASSWORD: pasha

volumes:
  postgres:
    driver: local

