// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// NewBindUserWalletParams creates a new BindUserWalletParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBindUserWalletParams() *BindUserWalletParams {
	return &BindUserWalletParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBindUserWalletParamsWithTimeout creates a new BindUserWalletParams object
// with the ability to set a timeout on a request.
func NewBindUserWalletParamsWithTimeout(timeout time.Duration) *BindUserWalletParams {
	return &BindUserWalletParams{
		timeout: timeout,
	}
}

// NewBindUserWalletParamsWithContext creates a new BindUserWalletParams object
// with the ability to set a context for a request.
func NewBindUserWalletParamsWithContext(ctx context.Context) *BindUserWalletParams {
	return &BindUserWalletParams{
		Context: ctx,
	}
}

// NewBindUserWalletParamsWithHTTPClient creates a new BindUserWalletParams object
// with the ability to set a custom HTTPClient for a request.
func NewBindUserWalletParamsWithHTTPClient(client *http.Client) *BindUserWalletParams {
	return &BindUserWalletParams{
		HTTPClient: client,
	}
}

/*
BindUserWalletParams contains all the parameters to send to the API endpoint

	for the bind user wallet operation.

	Typically these are written to a http.Request.
*/
type BindUserWalletParams struct {

	/* WalletBody.

	   Wallet body
	*/
	WalletBody *models.WalletBody

	/* TgID.

	   The tg ID of user
	*/
	TgID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the bind user wallet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BindUserWalletParams) WithDefaults() *BindUserWalletParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the bind user wallet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BindUserWalletParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the bind user wallet params
func (o *BindUserWalletParams) WithTimeout(timeout time.Duration) *BindUserWalletParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the bind user wallet params
func (o *BindUserWalletParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the bind user wallet params
func (o *BindUserWalletParams) WithContext(ctx context.Context) *BindUserWalletParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the bind user wallet params
func (o *BindUserWalletParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the bind user wallet params
func (o *BindUserWalletParams) WithHTTPClient(client *http.Client) *BindUserWalletParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the bind user wallet params
func (o *BindUserWalletParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWalletBody adds the walletBody to the bind user wallet params
func (o *BindUserWalletParams) WithWalletBody(walletBody *models.WalletBody) *BindUserWalletParams {
	o.SetWalletBody(walletBody)
	return o
}

// SetWalletBody adds the walletBody to the bind user wallet params
func (o *BindUserWalletParams) SetWalletBody(walletBody *models.WalletBody) {
	o.WalletBody = walletBody
}

// WithTgID adds the tgID to the bind user wallet params
func (o *BindUserWalletParams) WithTgID(tgID int64) *BindUserWalletParams {
	o.SetTgID(tgID)
	return o
}

// SetTgID adds the tgId to the bind user wallet params
func (o *BindUserWalletParams) SetTgID(tgID int64) {
	o.TgID = tgID
}

// WriteToRequest writes these params to a swagger request
func (o *BindUserWalletParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.WalletBody != nil {
		if err := r.SetBodyParam(o.WalletBody); err != nil {
			return err
		}
	}

	// path param tg_id
	if err := r.SetPathParam("tg_id", swag.FormatInt64(o.TgID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
