// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// ColectReferralEarnReader is a Reader for the ColectReferralEarn structure.
type ColectReferralEarnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ColectReferralEarnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewColectReferralEarnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewColectReferralEarnBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewColectReferralEarnForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewColectReferralEarnUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewColectReferralEarnInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /collect_referral_earn/{tg_id}] ColectReferralEarn", response, response.Code())
	}
}

// NewColectReferralEarnOK creates a ColectReferralEarnOK with default headers values
func NewColectReferralEarnOK() *ColectReferralEarnOK {
	return &ColectReferralEarnOK{}
}

/*
ColectReferralEarnOK describes a response with status code 200, with default header values.

Referral Balance Response
*/
type ColectReferralEarnOK struct {
	Payload *models.ReferralBalance
}

// IsSuccess returns true when this colect referral earn o k response has a 2xx status code
func (o *ColectReferralEarnOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this colect referral earn o k response has a 3xx status code
func (o *ColectReferralEarnOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this colect referral earn o k response has a 4xx status code
func (o *ColectReferralEarnOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this colect referral earn o k response has a 5xx status code
func (o *ColectReferralEarnOK) IsServerError() bool {
	return false
}

// IsCode returns true when this colect referral earn o k response a status code equal to that given
func (o *ColectReferralEarnOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the colect referral earn o k response
func (o *ColectReferralEarnOK) Code() int {
	return 200
}

func (o *ColectReferralEarnOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnOK %s", 200, payload)
}

func (o *ColectReferralEarnOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnOK %s", 200, payload)
}

func (o *ColectReferralEarnOK) GetPayload() *models.ReferralBalance {
	return o.Payload
}

func (o *ColectReferralEarnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReferralBalance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewColectReferralEarnBadRequest creates a ColectReferralEarnBadRequest with default headers values
func NewColectReferralEarnBadRequest() *ColectReferralEarnBadRequest {
	return &ColectReferralEarnBadRequest{}
}

/*
ColectReferralEarnBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ColectReferralEarnBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this colect referral earn bad request response has a 2xx status code
func (o *ColectReferralEarnBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this colect referral earn bad request response has a 3xx status code
func (o *ColectReferralEarnBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this colect referral earn bad request response has a 4xx status code
func (o *ColectReferralEarnBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this colect referral earn bad request response has a 5xx status code
func (o *ColectReferralEarnBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this colect referral earn bad request response a status code equal to that given
func (o *ColectReferralEarnBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the colect referral earn bad request response
func (o *ColectReferralEarnBadRequest) Code() int {
	return 400
}

func (o *ColectReferralEarnBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnBadRequest %s", 400, payload)
}

func (o *ColectReferralEarnBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnBadRequest %s", 400, payload)
}

func (o *ColectReferralEarnBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ColectReferralEarnBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewColectReferralEarnForbidden creates a ColectReferralEarnForbidden with default headers values
func NewColectReferralEarnForbidden() *ColectReferralEarnForbidden {
	return &ColectReferralEarnForbidden{}
}

/*
ColectReferralEarnForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ColectReferralEarnForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this colect referral earn forbidden response has a 2xx status code
func (o *ColectReferralEarnForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this colect referral earn forbidden response has a 3xx status code
func (o *ColectReferralEarnForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this colect referral earn forbidden response has a 4xx status code
func (o *ColectReferralEarnForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this colect referral earn forbidden response has a 5xx status code
func (o *ColectReferralEarnForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this colect referral earn forbidden response a status code equal to that given
func (o *ColectReferralEarnForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the colect referral earn forbidden response
func (o *ColectReferralEarnForbidden) Code() int {
	return 403
}

func (o *ColectReferralEarnForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnForbidden %s", 403, payload)
}

func (o *ColectReferralEarnForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnForbidden %s", 403, payload)
}

func (o *ColectReferralEarnForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *ColectReferralEarnForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewColectReferralEarnUnprocessableEntity creates a ColectReferralEarnUnprocessableEntity with default headers values
func NewColectReferralEarnUnprocessableEntity() *ColectReferralEarnUnprocessableEntity {
	return &ColectReferralEarnUnprocessableEntity{}
}

/*
ColectReferralEarnUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type ColectReferralEarnUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this colect referral earn unprocessable entity response has a 2xx status code
func (o *ColectReferralEarnUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this colect referral earn unprocessable entity response has a 3xx status code
func (o *ColectReferralEarnUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this colect referral earn unprocessable entity response has a 4xx status code
func (o *ColectReferralEarnUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this colect referral earn unprocessable entity response has a 5xx status code
func (o *ColectReferralEarnUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this colect referral earn unprocessable entity response a status code equal to that given
func (o *ColectReferralEarnUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the colect referral earn unprocessable entity response
func (o *ColectReferralEarnUnprocessableEntity) Code() int {
	return 422
}

func (o *ColectReferralEarnUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnUnprocessableEntity %s", 422, payload)
}

func (o *ColectReferralEarnUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnUnprocessableEntity %s", 422, payload)
}

func (o *ColectReferralEarnUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *ColectReferralEarnUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewColectReferralEarnInternalServerError creates a ColectReferralEarnInternalServerError with default headers values
func NewColectReferralEarnInternalServerError() *ColectReferralEarnInternalServerError {
	return &ColectReferralEarnInternalServerError{}
}

/*
ColectReferralEarnInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type ColectReferralEarnInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this colect referral earn internal server error response has a 2xx status code
func (o *ColectReferralEarnInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this colect referral earn internal server error response has a 3xx status code
func (o *ColectReferralEarnInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this colect referral earn internal server error response has a 4xx status code
func (o *ColectReferralEarnInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this colect referral earn internal server error response has a 5xx status code
func (o *ColectReferralEarnInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this colect referral earn internal server error response a status code equal to that given
func (o *ColectReferralEarnInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the colect referral earn internal server error response
func (o *ColectReferralEarnInternalServerError) Code() int {
	return 500
}

func (o *ColectReferralEarnInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnInternalServerError %s", 500, payload)
}

func (o *ColectReferralEarnInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /collect_referral_earn/{tg_id}][%d] colectReferralEarnInternalServerError %s", 500, payload)
}

func (o *ColectReferralEarnInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ColectReferralEarnInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
