// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewColectReferralEarnParams creates a new ColectReferralEarnParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewColectReferralEarnParams() *ColectReferralEarnParams {
	return &ColectReferralEarnParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewColectReferralEarnParamsWithTimeout creates a new ColectReferralEarnParams object
// with the ability to set a timeout on a request.
func NewColectReferralEarnParamsWithTimeout(timeout time.Duration) *ColectReferralEarnParams {
	return &ColectReferralEarnParams{
		timeout: timeout,
	}
}

// NewColectReferralEarnParamsWithContext creates a new ColectReferralEarnParams object
// with the ability to set a context for a request.
func NewColectReferralEarnParamsWithContext(ctx context.Context) *ColectReferralEarnParams {
	return &ColectReferralEarnParams{
		Context: ctx,
	}
}

// NewColectReferralEarnParamsWithHTTPClient creates a new ColectReferralEarnParams object
// with the ability to set a custom HTTPClient for a request.
func NewColectReferralEarnParamsWithHTTPClient(client *http.Client) *ColectReferralEarnParams {
	return &ColectReferralEarnParams{
		HTTPClient: client,
	}
}

/*
ColectReferralEarnParams contains all the parameters to send to the API endpoint

	for the colect referral earn operation.

	Typically these are written to a http.Request.
*/
type ColectReferralEarnParams struct {

	/* TgID.

	   The tg ID of user
	*/
	TgID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the colect referral earn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ColectReferralEarnParams) WithDefaults() *ColectReferralEarnParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the colect referral earn params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ColectReferralEarnParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the colect referral earn params
func (o *ColectReferralEarnParams) WithTimeout(timeout time.Duration) *ColectReferralEarnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the colect referral earn params
func (o *ColectReferralEarnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the colect referral earn params
func (o *ColectReferralEarnParams) WithContext(ctx context.Context) *ColectReferralEarnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the colect referral earn params
func (o *ColectReferralEarnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the colect referral earn params
func (o *ColectReferralEarnParams) WithHTTPClient(client *http.Client) *ColectReferralEarnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the colect referral earn params
func (o *ColectReferralEarnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTgID adds the tgID to the colect referral earn params
func (o *ColectReferralEarnParams) WithTgID(tgID int64) *ColectReferralEarnParams {
	o.SetTgID(tgID)
	return o
}

// SetTgID adds the tgId to the colect referral earn params
func (o *ColectReferralEarnParams) SetTgID(tgID int64) {
	o.TgID = tgID
}

// WriteToRequest writes these params to a swagger request
func (o *ColectReferralEarnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tg_id
	if err := r.SetPathParam("tg_id", swag.FormatInt64(o.TgID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
