// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// CreateReferralUserReader is a Reader for the CreateReferralUser structure.
type CreateReferralUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateReferralUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateReferralUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateReferralUserBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateReferralUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateReferralUserUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateReferralUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /create_referral_user/{tg_id}] CreateReferralUser", response, response.Code())
	}
}

// NewCreateReferralUserOK creates a CreateReferralUserOK with default headers values
func NewCreateReferralUserOK() *CreateReferralUserOK {
	return &CreateReferralUserOK{}
}

/*
CreateReferralUserOK describes a response with status code 200, with default header values.

Referral Link Response
*/
type CreateReferralUserOK struct {
	Payload *models.Error
}

// IsSuccess returns true when this create referral user o k response has a 2xx status code
func (o *CreateReferralUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create referral user o k response has a 3xx status code
func (o *CreateReferralUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create referral user o k response has a 4xx status code
func (o *CreateReferralUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create referral user o k response has a 5xx status code
func (o *CreateReferralUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create referral user o k response a status code equal to that given
func (o *CreateReferralUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create referral user o k response
func (o *CreateReferralUserOK) Code() int {
	return 200
}

func (o *CreateReferralUserOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserOK %s", 200, payload)
}

func (o *CreateReferralUserOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserOK %s", 200, payload)
}

func (o *CreateReferralUserOK) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateReferralUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateReferralUserBadRequest creates a CreateReferralUserBadRequest with default headers values
func NewCreateReferralUserBadRequest() *CreateReferralUserBadRequest {
	return &CreateReferralUserBadRequest{}
}

/*
CreateReferralUserBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateReferralUserBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create referral user bad request response has a 2xx status code
func (o *CreateReferralUserBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create referral user bad request response has a 3xx status code
func (o *CreateReferralUserBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create referral user bad request response has a 4xx status code
func (o *CreateReferralUserBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create referral user bad request response has a 5xx status code
func (o *CreateReferralUserBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create referral user bad request response a status code equal to that given
func (o *CreateReferralUserBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create referral user bad request response
func (o *CreateReferralUserBadRequest) Code() int {
	return 400
}

func (o *CreateReferralUserBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserBadRequest %s", 400, payload)
}

func (o *CreateReferralUserBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserBadRequest %s", 400, payload)
}

func (o *CreateReferralUserBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateReferralUserBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateReferralUserForbidden creates a CreateReferralUserForbidden with default headers values
func NewCreateReferralUserForbidden() *CreateReferralUserForbidden {
	return &CreateReferralUserForbidden{}
}

/*
CreateReferralUserForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateReferralUserForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this create referral user forbidden response has a 2xx status code
func (o *CreateReferralUserForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create referral user forbidden response has a 3xx status code
func (o *CreateReferralUserForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create referral user forbidden response has a 4xx status code
func (o *CreateReferralUserForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create referral user forbidden response has a 5xx status code
func (o *CreateReferralUserForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create referral user forbidden response a status code equal to that given
func (o *CreateReferralUserForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create referral user forbidden response
func (o *CreateReferralUserForbidden) Code() int {
	return 403
}

func (o *CreateReferralUserForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserForbidden %s", 403, payload)
}

func (o *CreateReferralUserForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserForbidden %s", 403, payload)
}

func (o *CreateReferralUserForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateReferralUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateReferralUserUnprocessableEntity creates a CreateReferralUserUnprocessableEntity with default headers values
func NewCreateReferralUserUnprocessableEntity() *CreateReferralUserUnprocessableEntity {
	return &CreateReferralUserUnprocessableEntity{}
}

/*
CreateReferralUserUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type CreateReferralUserUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this create referral user unprocessable entity response has a 2xx status code
func (o *CreateReferralUserUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create referral user unprocessable entity response has a 3xx status code
func (o *CreateReferralUserUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create referral user unprocessable entity response has a 4xx status code
func (o *CreateReferralUserUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this create referral user unprocessable entity response has a 5xx status code
func (o *CreateReferralUserUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this create referral user unprocessable entity response a status code equal to that given
func (o *CreateReferralUserUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the create referral user unprocessable entity response
func (o *CreateReferralUserUnprocessableEntity) Code() int {
	return 422
}

func (o *CreateReferralUserUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserUnprocessableEntity %s", 422, payload)
}

func (o *CreateReferralUserUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserUnprocessableEntity %s", 422, payload)
}

func (o *CreateReferralUserUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateReferralUserUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateReferralUserInternalServerError creates a CreateReferralUserInternalServerError with default headers values
func NewCreateReferralUserInternalServerError() *CreateReferralUserInternalServerError {
	return &CreateReferralUserInternalServerError{}
}

/*
CreateReferralUserInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type CreateReferralUserInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this create referral user internal server error response has a 2xx status code
func (o *CreateReferralUserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create referral user internal server error response has a 3xx status code
func (o *CreateReferralUserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create referral user internal server error response has a 4xx status code
func (o *CreateReferralUserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create referral user internal server error response has a 5xx status code
func (o *CreateReferralUserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create referral user internal server error response a status code equal to that given
func (o *CreateReferralUserInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create referral user internal server error response
func (o *CreateReferralUserInternalServerError) Code() int {
	return 500
}

func (o *CreateReferralUserInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserInternalServerError %s", 500, payload)
}

func (o *CreateReferralUserInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /create_referral_user/{tg_id}][%d] createReferralUserInternalServerError %s", 500, payload)
}

func (o *CreateReferralUserInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateReferralUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
