// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// NewCreateReferralUserParams creates a new CreateReferralUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateReferralUserParams() *CreateReferralUserParams {
	return &CreateReferralUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateReferralUserParamsWithTimeout creates a new CreateReferralUserParams object
// with the ability to set a timeout on a request.
func NewCreateReferralUserParamsWithTimeout(timeout time.Duration) *CreateReferralUserParams {
	return &CreateReferralUserParams{
		timeout: timeout,
	}
}

// NewCreateReferralUserParamsWithContext creates a new CreateReferralUserParams object
// with the ability to set a context for a request.
func NewCreateReferralUserParamsWithContext(ctx context.Context) *CreateReferralUserParams {
	return &CreateReferralUserParams{
		Context: ctx,
	}
}

// NewCreateReferralUserParamsWithHTTPClient creates a new CreateReferralUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateReferralUserParamsWithHTTPClient(client *http.Client) *CreateReferralUserParams {
	return &CreateReferralUserParams{
		HTTPClient: client,
	}
}

/*
CreateReferralUserParams contains all the parameters to send to the API endpoint

	for the create referral user operation.

	Typically these are written to a http.Request.
*/
type CreateReferralUserParams struct {

	/* ReferralLink.

	   Referral Link Body
	*/
	ReferralLink *models.ReferralLink

	/* TgID.

	   The tg ID of user
	*/
	TgID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create referral user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateReferralUserParams) WithDefaults() *CreateReferralUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create referral user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateReferralUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create referral user params
func (o *CreateReferralUserParams) WithTimeout(timeout time.Duration) *CreateReferralUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create referral user params
func (o *CreateReferralUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create referral user params
func (o *CreateReferralUserParams) WithContext(ctx context.Context) *CreateReferralUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create referral user params
func (o *CreateReferralUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create referral user params
func (o *CreateReferralUserParams) WithHTTPClient(client *http.Client) *CreateReferralUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create referral user params
func (o *CreateReferralUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReferralLink adds the referralLink to the create referral user params
func (o *CreateReferralUserParams) WithReferralLink(referralLink *models.ReferralLink) *CreateReferralUserParams {
	o.SetReferralLink(referralLink)
	return o
}

// SetReferralLink adds the referralLink to the create referral user params
func (o *CreateReferralUserParams) SetReferralLink(referralLink *models.ReferralLink) {
	o.ReferralLink = referralLink
}

// WithTgID adds the tgID to the create referral user params
func (o *CreateReferralUserParams) WithTgID(tgID int64) *CreateReferralUserParams {
	o.SetTgID(tgID)
	return o
}

// SetTgID adds the tgId to the create referral user params
func (o *CreateReferralUserParams) SetTgID(tgID int64) {
	o.TgID = tgID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateReferralUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ReferralLink != nil {
		if err := r.SetBodyParam(o.ReferralLink); err != nil {
			return err
		}
	}

	// path param tg_id
	if err := r.SetPathParam("tg_id", swag.FormatInt64(o.TgID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
