// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetReferralLinkParams creates a new GetReferralLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReferralLinkParams() *GetReferralLinkParams {
	return &GetReferralLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReferralLinkParamsWithTimeout creates a new GetReferralLinkParams object
// with the ability to set a timeout on a request.
func NewGetReferralLinkParamsWithTimeout(timeout time.Duration) *GetReferralLinkParams {
	return &GetReferralLinkParams{
		timeout: timeout,
	}
}

// NewGetReferralLinkParamsWithContext creates a new GetReferralLinkParams object
// with the ability to set a context for a request.
func NewGetReferralLinkParamsWithContext(ctx context.Context) *GetReferralLinkParams {
	return &GetReferralLinkParams{
		Context: ctx,
	}
}

// NewGetReferralLinkParamsWithHTTPClient creates a new GetReferralLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReferralLinkParamsWithHTTPClient(client *http.Client) *GetReferralLinkParams {
	return &GetReferralLinkParams{
		HTTPClient: client,
	}
}

/*
GetReferralLinkParams contains all the parameters to send to the API endpoint

	for the get referral link operation.

	Typically these are written to a http.Request.
*/
type GetReferralLinkParams struct {

	/* TgID.

	   The tg ID of user
	*/
	TgID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get referral link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReferralLinkParams) WithDefaults() *GetReferralLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get referral link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReferralLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get referral link params
func (o *GetReferralLinkParams) WithTimeout(timeout time.Duration) *GetReferralLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get referral link params
func (o *GetReferralLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get referral link params
func (o *GetReferralLinkParams) WithContext(ctx context.Context) *GetReferralLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get referral link params
func (o *GetReferralLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get referral link params
func (o *GetReferralLinkParams) WithHTTPClient(client *http.Client) *GetReferralLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get referral link params
func (o *GetReferralLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTgID adds the tgID to the get referral link params
func (o *GetReferralLinkParams) WithTgID(tgID int64) *GetReferralLinkParams {
	o.SetTgID(tgID)
	return o
}

// SetTgID adds the tgId to the get referral link params
func (o *GetReferralLinkParams) SetTgID(tgID int64) {
	o.TgID = tgID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReferralLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tg_id
	if err := r.SetPathParam("tg_id", swag.FormatInt64(o.TgID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
