// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStopEnergyOfflineParams creates a new StopEnergyOfflineParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopEnergyOfflineParams() *StopEnergyOfflineParams {
	return &StopEnergyOfflineParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopEnergyOfflineParamsWithTimeout creates a new StopEnergyOfflineParams object
// with the ability to set a timeout on a request.
func NewStopEnergyOfflineParamsWithTimeout(timeout time.Duration) *StopEnergyOfflineParams {
	return &StopEnergyOfflineParams{
		timeout: timeout,
	}
}

// NewStopEnergyOfflineParamsWithContext creates a new StopEnergyOfflineParams object
// with the ability to set a context for a request.
func NewStopEnergyOfflineParamsWithContext(ctx context.Context) *StopEnergyOfflineParams {
	return &StopEnergyOfflineParams{
		Context: ctx,
	}
}

// NewStopEnergyOfflineParamsWithHTTPClient creates a new StopEnergyOfflineParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopEnergyOfflineParamsWithHTTPClient(client *http.Client) *StopEnergyOfflineParams {
	return &StopEnergyOfflineParams{
		HTTPClient: client,
	}
}

/*
StopEnergyOfflineParams contains all the parameters to send to the API endpoint

	for the stop energy offline operation.

	Typically these are written to a http.Request.
*/
type StopEnergyOfflineParams struct {

	/* TgID.

	   The tg ID of user
	*/
	TgID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop energy offline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopEnergyOfflineParams) WithDefaults() *StopEnergyOfflineParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop energy offline params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopEnergyOfflineParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop energy offline params
func (o *StopEnergyOfflineParams) WithTimeout(timeout time.Duration) *StopEnergyOfflineParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop energy offline params
func (o *StopEnergyOfflineParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop energy offline params
func (o *StopEnergyOfflineParams) WithContext(ctx context.Context) *StopEnergyOfflineParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop energy offline params
func (o *StopEnergyOfflineParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop energy offline params
func (o *StopEnergyOfflineParams) WithHTTPClient(client *http.Client) *StopEnergyOfflineParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop energy offline params
func (o *StopEnergyOfflineParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTgID adds the tgID to the stop energy offline params
func (o *StopEnergyOfflineParams) WithTgID(tgID int64) *StopEnergyOfflineParams {
	o.SetTgID(tgID)
	return o
}

// SetTgID adds the tgId to the stop energy offline params
func (o *StopEnergyOfflineParams) SetTgID(tgID int64) {
	o.TgID = tgID
}

// WriteToRequest writes these params to a swagger request
func (o *StopEnergyOfflineParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tg_id
	if err := r.SetPathParam("tg_id", swag.FormatInt64(o.TgID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
