// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewStopAutoClickerParams creates a new StopAutoClickerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopAutoClickerParams() *StopAutoClickerParams {
	return &StopAutoClickerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopAutoClickerParamsWithTimeout creates a new StopAutoClickerParams object
// with the ability to set a timeout on a request.
func NewStopAutoClickerParamsWithTimeout(timeout time.Duration) *StopAutoClickerParams {
	return &StopAutoClickerParams{
		timeout: timeout,
	}
}

// NewStopAutoClickerParamsWithContext creates a new StopAutoClickerParams object
// with the ability to set a context for a request.
func NewStopAutoClickerParamsWithContext(ctx context.Context) *StopAutoClickerParams {
	return &StopAutoClickerParams{
		Context: ctx,
	}
}

// NewStopAutoClickerParamsWithHTTPClient creates a new StopAutoClickerParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopAutoClickerParamsWithHTTPClient(client *http.Client) *StopAutoClickerParams {
	return &StopAutoClickerParams{
		HTTPClient: client,
	}
}

/*
StopAutoClickerParams contains all the parameters to send to the API endpoint

	for the stop auto clicker operation.

	Typically these are written to a http.Request.
*/
type StopAutoClickerParams struct {

	/* TgID.

	   The tg ID of user
	*/
	TgID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop auto clicker params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopAutoClickerParams) WithDefaults() *StopAutoClickerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop auto clicker params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopAutoClickerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop auto clicker params
func (o *StopAutoClickerParams) WithTimeout(timeout time.Duration) *StopAutoClickerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop auto clicker params
func (o *StopAutoClickerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop auto clicker params
func (o *StopAutoClickerParams) WithContext(ctx context.Context) *StopAutoClickerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop auto clicker params
func (o *StopAutoClickerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop auto clicker params
func (o *StopAutoClickerParams) WithHTTPClient(client *http.Client) *StopAutoClickerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop auto clicker params
func (o *StopAutoClickerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTgID adds the tgID to the stop auto clicker params
func (o *StopAutoClickerParams) WithTgID(tgID int64) *StopAutoClickerParams {
	o.SetTgID(tgID)
	return o
}

// SetTgID adds the tgId to the stop auto clicker params
func (o *StopAutoClickerParams) SetTgID(tgID int64) {
	o.TgID = tgID
}

// WriteToRequest writes these params to a swagger request
func (o *StopAutoClickerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tg_id
	if err := r.SetPathParam("tg_id", swag.FormatInt64(o.TgID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
