// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// NewTransitNearParams creates a new TransitNearParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTransitNearParams() *TransitNearParams {
	return &TransitNearParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTransitNearParamsWithTimeout creates a new TransitNearParams object
// with the ability to set a timeout on a request.
func NewTransitNearParamsWithTimeout(timeout time.Duration) *TransitNearParams {
	return &TransitNearParams{
		timeout: timeout,
	}
}

// NewTransitNearParamsWithContext creates a new TransitNearParams object
// with the ability to set a context for a request.
func NewTransitNearParamsWithContext(ctx context.Context) *TransitNearParams {
	return &TransitNearParams{
		Context: ctx,
	}
}

// NewTransitNearParamsWithHTTPClient creates a new TransitNearParams object
// with the ability to set a custom HTTPClient for a request.
func NewTransitNearParamsWithHTTPClient(client *http.Client) *TransitNearParams {
	return &TransitNearParams{
		HTTPClient: client,
	}
}

/*
TransitNearParams contains all the parameters to send to the API endpoint

	for the transit near operation.

	Typically these are written to a http.Request.
*/
type TransitNearParams struct {

	/* GetNearBody.

	   Get Near
	*/
	GetNearBody *models.GetNearBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the transit near params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransitNearParams) WithDefaults() *TransitNearParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the transit near params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransitNearParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the transit near params
func (o *TransitNearParams) WithTimeout(timeout time.Duration) *TransitNearParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transit near params
func (o *TransitNearParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transit near params
func (o *TransitNearParams) WithContext(ctx context.Context) *TransitNearParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transit near params
func (o *TransitNearParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transit near params
func (o *TransitNearParams) WithHTTPClient(client *http.Client) *TransitNearParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transit near params
func (o *TransitNearParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGetNearBody adds the getNearBody to the transit near params
func (o *TransitNearParams) WithGetNearBody(getNearBody *models.GetNearBody) *TransitNearParams {
	o.SetGetNearBody(getNearBody)
	return o
}

// SetGetNearBody adds the getNearBody to the transit near params
func (o *TransitNearParams) SetGetNearBody(getNearBody *models.GetNearBody) {
	o.GetNearBody = getNearBody
}

// WriteToRequest writes these params to a swagger request
func (o *TransitNearParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.GetNearBody != nil {
		if err := r.SetBodyParam(o.GetNearBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
