// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// NewUpdateUserCardParams creates a new UpdateUserCardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateUserCardParams() *UpdateUserCardParams {
	return &UpdateUserCardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateUserCardParamsWithTimeout creates a new UpdateUserCardParams object
// with the ability to set a timeout on a request.
func NewUpdateUserCardParamsWithTimeout(timeout time.Duration) *UpdateUserCardParams {
	return &UpdateUserCardParams{
		timeout: timeout,
	}
}

// NewUpdateUserCardParamsWithContext creates a new UpdateUserCardParams object
// with the ability to set a context for a request.
func NewUpdateUserCardParamsWithContext(ctx context.Context) *UpdateUserCardParams {
	return &UpdateUserCardParams{
		Context: ctx,
	}
}

// NewUpdateUserCardParamsWithHTTPClient creates a new UpdateUserCardParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateUserCardParamsWithHTTPClient(client *http.Client) *UpdateUserCardParams {
	return &UpdateUserCardParams{
		HTTPClient: client,
	}
}

/*
UpdateUserCardParams contains all the parameters to send to the API endpoint

	for the update user card operation.

	Typically these are written to a http.Request.
*/
type UpdateUserCardParams struct {

	/* CardUpdateBody.

	   Card Update Body
	*/
	CardUpdateBody *models.CardUpdateBody

	/* TgID.

	   The tg ID of user
	*/
	TgID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update user card params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserCardParams) WithDefaults() *UpdateUserCardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update user card params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateUserCardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update user card params
func (o *UpdateUserCardParams) WithTimeout(timeout time.Duration) *UpdateUserCardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update user card params
func (o *UpdateUserCardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update user card params
func (o *UpdateUserCardParams) WithContext(ctx context.Context) *UpdateUserCardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update user card params
func (o *UpdateUserCardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update user card params
func (o *UpdateUserCardParams) WithHTTPClient(client *http.Client) *UpdateUserCardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update user card params
func (o *UpdateUserCardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCardUpdateBody adds the cardUpdateBody to the update user card params
func (o *UpdateUserCardParams) WithCardUpdateBody(cardUpdateBody *models.CardUpdateBody) *UpdateUserCardParams {
	o.SetCardUpdateBody(cardUpdateBody)
	return o
}

// SetCardUpdateBody adds the cardUpdateBody to the update user card params
func (o *UpdateUserCardParams) SetCardUpdateBody(cardUpdateBody *models.CardUpdateBody) {
	o.CardUpdateBody = cardUpdateBody
}

// WithTgID adds the tgID to the update user card params
func (o *UpdateUserCardParams) WithTgID(tgID int64) *UpdateUserCardParams {
	o.SetTgID(tgID)
	return o
}

// SetTgID adds the tgId to the update user card params
func (o *UpdateUserCardParams) SetTgID(tgID int64) {
	o.TgID = tgID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateUserCardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.CardUpdateBody != nil {
		if err := r.SetBodyParam(o.CardUpdateBody); err != nil {
			return err
		}
	}

	// path param tg_id
	if err := r.SetPathParam("tg_id", swag.FormatInt64(o.TgID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
