// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// CreateReferralUserOKCode is the HTTP code returned for type CreateReferralUserOK
const CreateReferralUserOKCode int = 200

/*
CreateReferralUserOK Referral Link Response

swagger:response createReferralUserOK
*/
type CreateReferralUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateReferralUserOK creates CreateReferralUserOK with default headers values
func NewCreateReferralUserOK() *CreateReferralUserOK {

	return &CreateReferralUserOK{}
}

// WithPayload adds the payload to the create referral user o k response
func (o *CreateReferralUserOK) WithPayload(payload *models.Error) *CreateReferralUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create referral user o k response
func (o *CreateReferralUserOK) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateReferralUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateReferralUserBadRequestCode is the HTTP code returned for type CreateReferralUserBadRequest
const CreateReferralUserBadRequestCode int = 400

/*
CreateReferralUserBadRequest Bad request

swagger:response createReferralUserBadRequest
*/
type CreateReferralUserBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateReferralUserBadRequest creates CreateReferralUserBadRequest with default headers values
func NewCreateReferralUserBadRequest() *CreateReferralUserBadRequest {

	return &CreateReferralUserBadRequest{}
}

// WithPayload adds the payload to the create referral user bad request response
func (o *CreateReferralUserBadRequest) WithPayload(payload *models.Error) *CreateReferralUserBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create referral user bad request response
func (o *CreateReferralUserBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateReferralUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateReferralUserForbiddenCode is the HTTP code returned for type CreateReferralUserForbidden
const CreateReferralUserForbiddenCode int = 403

/*
CreateReferralUserForbidden Forbidden

swagger:response createReferralUserForbidden
*/
type CreateReferralUserForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateReferralUserForbidden creates CreateReferralUserForbidden with default headers values
func NewCreateReferralUserForbidden() *CreateReferralUserForbidden {

	return &CreateReferralUserForbidden{}
}

// WithPayload adds the payload to the create referral user forbidden response
func (o *CreateReferralUserForbidden) WithPayload(payload *models.Error) *CreateReferralUserForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create referral user forbidden response
func (o *CreateReferralUserForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateReferralUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateReferralUserUnprocessableEntityCode is the HTTP code returned for type CreateReferralUserUnprocessableEntity
const CreateReferralUserUnprocessableEntityCode int = 422

/*
CreateReferralUserUnprocessableEntity Unprocessable Entity

swagger:response createReferralUserUnprocessableEntity
*/
type CreateReferralUserUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateReferralUserUnprocessableEntity creates CreateReferralUserUnprocessableEntity with default headers values
func NewCreateReferralUserUnprocessableEntity() *CreateReferralUserUnprocessableEntity {

	return &CreateReferralUserUnprocessableEntity{}
}

// WithPayload adds the payload to the create referral user unprocessable entity response
func (o *CreateReferralUserUnprocessableEntity) WithPayload(payload *models.Error) *CreateReferralUserUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create referral user unprocessable entity response
func (o *CreateReferralUserUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateReferralUserUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateReferralUserInternalServerErrorCode is the HTTP code returned for type CreateReferralUserInternalServerError
const CreateReferralUserInternalServerErrorCode int = 500

/*
CreateReferralUserInternalServerError Internal server error

swagger:response createReferralUserInternalServerError
*/
type CreateReferralUserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateReferralUserInternalServerError creates CreateReferralUserInternalServerError with default headers values
func NewCreateReferralUserInternalServerError() *CreateReferralUserInternalServerError {

	return &CreateReferralUserInternalServerError{}
}

// WithPayload adds the payload to the create referral user internal server error response
func (o *CreateReferralUserInternalServerError) WithPayload(payload *models.Error) *CreateReferralUserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create referral user internal server error response
func (o *CreateReferralUserInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateReferralUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
