// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateReferralUserHandlerFunc turns a function with the right signature into a create referral user handler
type CreateReferralUserHandlerFunc func(CreateReferralUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateReferralUserHandlerFunc) Handle(params CreateReferralUserParams) middleware.Responder {
	return fn(params)
}

// CreateReferralUserHandler interface for that can handle valid create referral user params
type CreateReferralUserHandler interface {
	Handle(CreateReferralUserParams) middleware.Responder
}

// NewCreateReferralUser creates a new http.Handler for the create referral user operation
func NewCreateReferralUser(ctx *middleware.Context, handler CreateReferralUserHandler) *CreateReferralUser {
	return &CreateReferralUser{Context: ctx, Handler: handler}
}

/*
	CreateReferralUser swagger:route POST /create_referral_user/{tg_id} User createReferralUser

Create Referral User
*/
type CreateReferralUser struct {
	Context *middleware.Context
	Handler CreateReferralUserHandler
}

func (o *CreateReferralUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateReferralUserParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
