// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// GetReferralLinkOKCode is the HTTP code returned for type GetReferralLinkOK
const GetReferralLinkOKCode int = 200

/*
GetReferralLinkOK Referral Link Response

swagger:response getReferralLinkOK
*/
type GetReferralLinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReferralLink `json:"body,omitempty"`
}

// NewGetReferralLinkOK creates GetReferralLinkOK with default headers values
func NewGetReferralLinkOK() *GetReferralLinkOK {

	return &GetReferralLinkOK{}
}

// WithPayload adds the payload to the get referral link o k response
func (o *GetReferralLinkOK) WithPayload(payload *models.ReferralLink) *GetReferralLinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get referral link o k response
func (o *GetReferralLinkOK) SetPayload(payload *models.ReferralLink) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReferralLinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReferralLinkBadRequestCode is the HTTP code returned for type GetReferralLinkBadRequest
const GetReferralLinkBadRequestCode int = 400

/*
GetReferralLinkBadRequest Bad request

swagger:response getReferralLinkBadRequest
*/
type GetReferralLinkBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReferralLinkBadRequest creates GetReferralLinkBadRequest with default headers values
func NewGetReferralLinkBadRequest() *GetReferralLinkBadRequest {

	return &GetReferralLinkBadRequest{}
}

// WithPayload adds the payload to the get referral link bad request response
func (o *GetReferralLinkBadRequest) WithPayload(payload *models.Error) *GetReferralLinkBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get referral link bad request response
func (o *GetReferralLinkBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReferralLinkBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReferralLinkForbiddenCode is the HTTP code returned for type GetReferralLinkForbidden
const GetReferralLinkForbiddenCode int = 403

/*
GetReferralLinkForbidden Forbidden

swagger:response getReferralLinkForbidden
*/
type GetReferralLinkForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReferralLinkForbidden creates GetReferralLinkForbidden with default headers values
func NewGetReferralLinkForbidden() *GetReferralLinkForbidden {

	return &GetReferralLinkForbidden{}
}

// WithPayload adds the payload to the get referral link forbidden response
func (o *GetReferralLinkForbidden) WithPayload(payload *models.Error) *GetReferralLinkForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get referral link forbidden response
func (o *GetReferralLinkForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReferralLinkForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReferralLinkUnprocessableEntityCode is the HTTP code returned for type GetReferralLinkUnprocessableEntity
const GetReferralLinkUnprocessableEntityCode int = 422

/*
GetReferralLinkUnprocessableEntity Unprocessable Entity

swagger:response getReferralLinkUnprocessableEntity
*/
type GetReferralLinkUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReferralLinkUnprocessableEntity creates GetReferralLinkUnprocessableEntity with default headers values
func NewGetReferralLinkUnprocessableEntity() *GetReferralLinkUnprocessableEntity {

	return &GetReferralLinkUnprocessableEntity{}
}

// WithPayload adds the payload to the get referral link unprocessable entity response
func (o *GetReferralLinkUnprocessableEntity) WithPayload(payload *models.Error) *GetReferralLinkUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get referral link unprocessable entity response
func (o *GetReferralLinkUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReferralLinkUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReferralLinkInternalServerErrorCode is the HTTP code returned for type GetReferralLinkInternalServerError
const GetReferralLinkInternalServerErrorCode int = 500

/*
GetReferralLinkInternalServerError Internal server error

swagger:response getReferralLinkInternalServerError
*/
type GetReferralLinkInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetReferralLinkInternalServerError creates GetReferralLinkInternalServerError with default headers values
func NewGetReferralLinkInternalServerError() *GetReferralLinkInternalServerError {

	return &GetReferralLinkInternalServerError{}
}

// WithPayload adds the payload to the get referral link internal server error response
func (o *GetReferralLinkInternalServerError) WithPayload(payload *models.Error) *GetReferralLinkInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get referral link internal server error response
func (o *GetReferralLinkInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReferralLinkInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
