// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUserCardsHandlerFunc turns a function with the right signature into a get user cards handler
type GetUserCardsHandlerFunc func(GetUserCardsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserCardsHandlerFunc) Handle(params GetUserCardsParams) middleware.Responder {
	return fn(params)
}

// GetUserCardsHandler interface for that can handle valid get user cards params
type GetUserCardsHandler interface {
	Handle(GetUserCardsParams) middleware.Responder
}

// NewGetUserCards creates a new http.Handler for the get user cards operation
func NewGetUserCards(ctx *middleware.Context, handler GetUserCardsHandler) *GetUserCards {
	return &GetUserCards{Context: ctx, Handler: handler}
}

/*
	GetUserCards swagger:route POST /get_user_cards/{tg_id} Cards getUserCards

Get User Cards
*/
type GetUserCards struct {
	Context *middleware.Context
	Handler GetUserCardsHandler
}

func (o *GetUserCards) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUserCardsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
