// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewMaxonBackAPI creates a new MaxonBack instance
func NewMaxonBackAPI(spec *loads.Document) *MaxonBackAPI {
	return &MaxonBackAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		GetUserProgressHandler: GetUserProgressHandlerFunc(func(params GetUserProgressParams) middleware.Responder {
			return middleware.NotImplemented("operation GetUserProgress has not yet been implemented")
		}),
		SaveProgressHandler: SaveProgressHandlerFunc(func(params SaveProgressParams) middleware.Responder {
			return middleware.NotImplemented("operation SaveProgress has not yet been implemented")
		}),
		StartAutoClickerHandler: StartAutoClickerHandlerFunc(func(params StartAutoClickerParams) middleware.Responder {
			return middleware.NotImplemented("operation StartAutoClicker has not yet been implemented")
		}),
		StartEnergyOfflineHandler: StartEnergyOfflineHandlerFunc(func(params StartEnergyOfflineParams) middleware.Responder {
			return middleware.NotImplemented("operation StartEnergyOffline has not yet been implemented")
		}),
		StopAutoClickerHandler: StopAutoClickerHandlerFunc(func(params StopAutoClickerParams) middleware.Responder {
			return middleware.NotImplemented("operation StopAutoClicker has not yet been implemented")
		}),
		StopEnergyOfflineHandler: StopEnergyOfflineHandlerFunc(func(params StopEnergyOfflineParams) middleware.Responder {
			return middleware.NotImplemented("operation StopEnergyOffline has not yet been implemented")
		}),
		TransitNearHandler: TransitNearHandlerFunc(func(params TransitNearParams) middleware.Responder {
			return middleware.NotImplemented("operation TransitNear has not yet been implemented")
		}),
		UpdateUserCardHandler: UpdateUserCardHandlerFunc(func(params UpdateUserCardParams) middleware.Responder {
			return middleware.NotImplemented("operation UpdateUserCard has not yet been implemented")
		}),
	}
}

/*MaxonBackAPI Makson zon zon */
type MaxonBackAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// GetUserProgressHandler sets the operation handler for the get user progress operation
	GetUserProgressHandler GetUserProgressHandler
	// SaveProgressHandler sets the operation handler for the save progress operation
	SaveProgressHandler SaveProgressHandler
	// StartAutoClickerHandler sets the operation handler for the start auto clicker operation
	StartAutoClickerHandler StartAutoClickerHandler
	// StartEnergyOfflineHandler sets the operation handler for the start energy offline operation
	StartEnergyOfflineHandler StartEnergyOfflineHandler
	// StopAutoClickerHandler sets the operation handler for the stop auto clicker operation
	StopAutoClickerHandler StopAutoClickerHandler
	// StopEnergyOfflineHandler sets the operation handler for the stop energy offline operation
	StopEnergyOfflineHandler StopEnergyOfflineHandler
	// TransitNearHandler sets the operation handler for the transit near operation
	TransitNearHandler TransitNearHandler
	// UpdateUserCardHandler sets the operation handler for the update user card operation
	UpdateUserCardHandler UpdateUserCardHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *MaxonBackAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *MaxonBackAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *MaxonBackAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *MaxonBackAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *MaxonBackAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *MaxonBackAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *MaxonBackAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *MaxonBackAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *MaxonBackAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the MaxonBackAPI
func (o *MaxonBackAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GetUserProgressHandler == nil {
		unregistered = append(unregistered, "GetUserProgressHandler")
	}
	if o.SaveProgressHandler == nil {
		unregistered = append(unregistered, "SaveProgressHandler")
	}
	if o.StartAutoClickerHandler == nil {
		unregistered = append(unregistered, "StartAutoClickerHandler")
	}
	if o.StartEnergyOfflineHandler == nil {
		unregistered = append(unregistered, "StartEnergyOfflineHandler")
	}
	if o.StopAutoClickerHandler == nil {
		unregistered = append(unregistered, "StopAutoClickerHandler")
	}
	if o.StopEnergyOfflineHandler == nil {
		unregistered = append(unregistered, "StopEnergyOfflineHandler")
	}
	if o.TransitNearHandler == nil {
		unregistered = append(unregistered, "TransitNearHandler")
	}
	if o.UpdateUserCardHandler == nil {
		unregistered = append(unregistered, "UpdateUserCardHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *MaxonBackAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *MaxonBackAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *MaxonBackAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *MaxonBackAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *MaxonBackAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *MaxonBackAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the maxon back API
func (o *MaxonBackAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *MaxonBackAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/get_user_progress/{tg_id}"] = NewGetUserProgress(o.context, o.GetUserProgressHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/save_progress"] = NewSaveProgress(o.context, o.SaveProgressHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/start_auto_clicker/{tg_id}"] = NewStartAutoClicker(o.context, o.StartAutoClickerHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/start_energy_collect/{tg_id}"] = NewStartEnergyOffline(o.context, o.StartEnergyOfflineHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/stop_auto_clicker/{tg_id}"] = NewStopAutoClicker(o.context, o.StopAutoClickerHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/stop_energy_collect/{tg_id}"] = NewStopEnergyOffline(o.context, o.StopEnergyOfflineHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/near_transaction"] = NewTransitNear(o.context, o.TransitNearHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/update_user_card/{tg_id}"] = NewUpdateUserCard(o.context, o.UpdateUserCardHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *MaxonBackAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *MaxonBackAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *MaxonBackAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *MaxonBackAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *MaxonBackAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
