// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SaveProgressHandlerFunc turns a function with the right signature into a save progress handler
type SaveProgressHandlerFunc func(SaveProgressParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SaveProgressHandlerFunc) Handle(params SaveProgressParams) middleware.Responder {
	return fn(params)
}

// SaveProgressHandler interface for that can handle valid save progress params
type SaveProgressHandler interface {
	Handle(SaveProgressParams) middleware.Responder
}

// NewSaveProgress creates a new http.Handler for the save progress operation
func NewSaveProgress(ctx *middleware.Context, handler SaveProgressHandler) *SaveProgress {
	return &SaveProgress{Context: ctx, Handler: handler}
}

/*
	SaveProgress swagger:route POST /save_progress Progress saveProgress

Save Progress
*/
type SaveProgress struct {
	Context *middleware.Context
	Handler SaveProgressHandler
}

func (o *SaveProgress) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSaveProgressParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
