// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StartAutoClickerHandlerFunc turns a function with the right signature into a start auto clicker handler
type StartAutoClickerHandlerFunc func(StartAutoClickerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn StartAutoClickerHandlerFunc) Handle(params StartAutoClickerParams) middleware.Responder {
	return fn(params)
}

// StartAutoClickerHandler interface for that can handle valid start auto clicker params
type StartAutoClickerHandler interface {
	Handle(StartAutoClickerParams) middleware.Responder
}

// NewStartAutoClicker creates a new http.Handler for the start auto clicker operation
func NewStartAutoClicker(ctx *middleware.Context, handler StartAutoClickerHandler) *StartAutoClicker {
	return &StartAutoClicker{Context: ctx, Handler: handler}
}

/*
	StartAutoClicker swagger:route POST /start_auto_clicker/{tg_id} AutoClicker startAutoClicker

Start Auto Clicker
*/
type StartAutoClicker struct {
	Context *middleware.Context
	Handler StartAutoClickerHandler
}

func (o *StartAutoClicker) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStartAutoClickerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
