// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pskoob/miniappBack/internal/api/definition"
)

// StopAutoClickerOKCode is the HTTP code returned for type StopAutoClickerOK
const StopAutoClickerOKCode int = 200

/*
StopAutoClickerOK Save Progress Response

swagger:response stopAutoClickerOK
*/
type StopAutoClickerOK struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStopAutoClickerOK creates StopAutoClickerOK with default headers values
func NewStopAutoClickerOK() *StopAutoClickerOK {

	return &StopAutoClickerOK{}
}

// WithPayload adds the payload to the stop auto clicker o k response
func (o *StopAutoClickerOK) WithPayload(payload *models.Error) *StopAutoClickerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stop auto clicker o k response
func (o *StopAutoClickerOK) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StopAutoClickerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StopAutoClickerBadRequestCode is the HTTP code returned for type StopAutoClickerBadRequest
const StopAutoClickerBadRequestCode int = 400

/*
StopAutoClickerBadRequest Bad request

swagger:response stopAutoClickerBadRequest
*/
type StopAutoClickerBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStopAutoClickerBadRequest creates StopAutoClickerBadRequest with default headers values
func NewStopAutoClickerBadRequest() *StopAutoClickerBadRequest {

	return &StopAutoClickerBadRequest{}
}

// WithPayload adds the payload to the stop auto clicker bad request response
func (o *StopAutoClickerBadRequest) WithPayload(payload *models.Error) *StopAutoClickerBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stop auto clicker bad request response
func (o *StopAutoClickerBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StopAutoClickerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StopAutoClickerForbiddenCode is the HTTP code returned for type StopAutoClickerForbidden
const StopAutoClickerForbiddenCode int = 403

/*
StopAutoClickerForbidden Forbidden

swagger:response stopAutoClickerForbidden
*/
type StopAutoClickerForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStopAutoClickerForbidden creates StopAutoClickerForbidden with default headers values
func NewStopAutoClickerForbidden() *StopAutoClickerForbidden {

	return &StopAutoClickerForbidden{}
}

// WithPayload adds the payload to the stop auto clicker forbidden response
func (o *StopAutoClickerForbidden) WithPayload(payload *models.Error) *StopAutoClickerForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stop auto clicker forbidden response
func (o *StopAutoClickerForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StopAutoClickerForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StopAutoClickerUnprocessableEntityCode is the HTTP code returned for type StopAutoClickerUnprocessableEntity
const StopAutoClickerUnprocessableEntityCode int = 422

/*
StopAutoClickerUnprocessableEntity Unprocessable Entity

swagger:response stopAutoClickerUnprocessableEntity
*/
type StopAutoClickerUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStopAutoClickerUnprocessableEntity creates StopAutoClickerUnprocessableEntity with default headers values
func NewStopAutoClickerUnprocessableEntity() *StopAutoClickerUnprocessableEntity {

	return &StopAutoClickerUnprocessableEntity{}
}

// WithPayload adds the payload to the stop auto clicker unprocessable entity response
func (o *StopAutoClickerUnprocessableEntity) WithPayload(payload *models.Error) *StopAutoClickerUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stop auto clicker unprocessable entity response
func (o *StopAutoClickerUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StopAutoClickerUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StopAutoClickerInternalServerErrorCode is the HTTP code returned for type StopAutoClickerInternalServerError
const StopAutoClickerInternalServerErrorCode int = 500

/*
StopAutoClickerInternalServerError Internal server error

swagger:response stopAutoClickerInternalServerError
*/
type StopAutoClickerInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStopAutoClickerInternalServerError creates StopAutoClickerInternalServerError with default headers values
func NewStopAutoClickerInternalServerError() *StopAutoClickerInternalServerError {

	return &StopAutoClickerInternalServerError{}
}

// WithPayload adds the payload to the stop auto clicker internal server error response
func (o *StopAutoClickerInternalServerError) WithPayload(payload *models.Error) *StopAutoClickerInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the stop auto clicker internal server error response
func (o *StopAutoClickerInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StopAutoClickerInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
