// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StopEnergyOfflineHandlerFunc turns a function with the right signature into a stop energy offline handler
type StopEnergyOfflineHandlerFunc func(StopEnergyOfflineParams) middleware.Responder

// Handle executing the request and returning a response
func (fn StopEnergyOfflineHandlerFunc) Handle(params StopEnergyOfflineParams) middleware.Responder {
	return fn(params)
}

// StopEnergyOfflineHandler interface for that can handle valid stop energy offline params
type StopEnergyOfflineHandler interface {
	Handle(StopEnergyOfflineParams) middleware.Responder
}

// NewStopEnergyOffline creates a new http.Handler for the stop energy offline operation
func NewStopEnergyOffline(ctx *middleware.Context, handler StopEnergyOfflineHandler) *StopEnergyOffline {
	return &StopEnergyOffline{Context: ctx, Handler: handler}
}

/*
	StopEnergyOffline swagger:route POST /stop_energy_collect/{tg_id} Energy stopEnergyOffline

Stop Energy Offline
*/
type StopEnergyOffline struct {
	Context *middleware.Context
	Handler StopEnergyOfflineHandler
}

func (o *StopEnergyOffline) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStopEnergyOfflineParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
