// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StopAutoClickerHandlerFunc turns a function with the right signature into a stop auto clicker handler
type StopAutoClickerHandlerFunc func(StopAutoClickerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn StopAutoClickerHandlerFunc) Handle(params StopAutoClickerParams) middleware.Responder {
	return fn(params)
}

// StopAutoClickerHandler interface for that can handle valid stop auto clicker params
type StopAutoClickerHandler interface {
	Handle(StopAutoClickerParams) middleware.Responder
}

// NewStopAutoClicker creates a new http.Handler for the stop auto clicker operation
func NewStopAutoClicker(ctx *middleware.Context, handler StopAutoClickerHandler) *StopAutoClicker {
	return &StopAutoClicker{Context: ctx, Handler: handler}
}

/*
	StopAutoClicker swagger:route POST /stop_auto_clicker/{tg_id} AutoClicker stopAutoClicker

Stop Auto Clicker
*/
type StopAutoClicker struct {
	Context *middleware.Context
	Handler StopAutoClickerHandler
}

func (o *StopAutoClicker) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStopAutoClickerParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
