swagger: '2.0'

info:
  title: maxon back
  version: development
  description: Makson zon zon

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

consumes:
  - application/json

produces:
  - application/json

paths:

  /save_progress:
    post:
      summary: Save Progress
      operationId: SaveProgress
      tags: 
        - Progress
      parameters:
        - name: Progress
          description: Save progress body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Progress'
      responses:
        200:
          description: Save Progress Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /get_user_progress/{tg_id}:
    get:
      summary: Get User Progress
      operationId: GetUserProgress
      tags: 
        - Progress
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Get User Progress Response
          schema:
            $ref: '#/definitions/User'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /start_auto_clicker/{tg_id}:
    post:
      summary: Start Auto Clicker
      operationId: StartAutoClicker
      tags: 
        - AutoClicker
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Save Progress Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /stop_auto_clicker/{tg_id}:
    post:
      summary: Stop Auto Clicker
      operationId: StopAutoClicker
      tags: 
        - AutoClicker
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Save Progress Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      

definitions:

  Progress:
    type: object
    required:
      - tg_id
      - clickCount
      - upgradeLevel
      - upgradeEnergy
      - hasAutoClicker
    properties:
      tg_id:
        type: integer
      clickCount:
        type: integer
      upgradeLevel:
        type: integer
      upgradeEnergy:
        type: integer
      hasAutoClicker:
        type: boolean

  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  User:
    type: object
    required:
      - tg_id
      - clickCount
      - upgradeLevel
      - upgrade_energy
      - hasAutoClicker
    properties:
      tg_id:
        type: integer
      upgrade_energy:
        type: integer
      upgradeLevel:
        type: integer
      clickCount:
        type: integer
      hasAutoClicker:
        type: boolean