swagger: '2.0'

info:
  title: maxon back
  version: development
  description: Makson zon zon

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

consumes:
  - application/json

produces:
  - application/json

paths:

  /save_progress/{tg_id}:
    post:
      summary: Save Progress
      operationId: SaveProgress
      tags: 
        - Progress
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
        - name: TapTokenBody
          description: Tap Token Body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TapTokenBody'
      responses:
        200:
          description: Save Progress Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /get_user/{tg_id}:
    get:
      summary: Get User Progress
      operationId: GetUserProgress
      tags: 
        - Progress
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Get User Progress Response
          schema:
            $ref: '#/definitions/User'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /start_auto_clicker/{tg_id}:
    post:
      summary: Start Auto Clicker
      operationId: StartAutoClicker
      tags: 
        - AutoClicker
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Save Progress Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /stop_auto_clicker/{tg_id}:
    post:
      summary: Stop Auto Clicker
      operationId: StopAutoClicker
      tags: 
        - AutoClicker
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Save Progress Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /start_energy_collect/{tg_id}:
    post:
      summary: Start Energy Offline
      operationId: StartEnergyOffline
      tags: 
        - Energy
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Start Collect Energy Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /stop_energy_collect/{tg_id}:
    post:
      summary: Stop Energy Offline
      operationId: StopEnergyOffline
      tags: 
        - Energy
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
      responses:
        200:
          description: Stop Collect Energy Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /update_user_card/{tg_id}:
    post:
      summary: Update User Card
      operationId: UpdateUserCard
      tags: 
        - Cards
      parameters:
        - name: tg_id
          in: path
          required: true
          type: integer
          description: The tg ID of user
        - name: CardUpdateBody
          description: Card Update Body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CardUpdateBody'
      responses:
        200:
          description: Update Card Response
          schema:
            $ref: '#/definitions/CardBody'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

  /near_transaction:
    post:
      summary: Transit Near
      operationId: TransitNear
      tags: 
        - Near
      parameters:
        - name: GetNearBody
          description: Get Near
          in: body
          required: true
          schema:
            $ref: '#/definitions/GetNearBody'
      responses:
        200:
          description: Successful Transit Near Response
          schema:
            $ref: '#/definitions/NearTransit'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      

definitions:

  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string

  User:
    type: object
    required:
      - tg_id
      - balance
      - wallet
      - username
    properties:
      tg_id:
        type: integer
      balance:
        type: integer
      upgrade_level:
        type: integer
      wallet:
        type: string
      username:
        type: string

  NearTransit:
    type: object
    properties:
      result:
        type: string

  GetNearBody:
    type: object
    properties:
      receiving_wallet:
        type: string
      amount:
        type: number
      token_contract:
        type: string

  CardBody:
    type: object
    properties:
      user_id:
        type: integer
      card_id:
        type: integer
      card_name:
        type: string
      current_level:
        type: integer
      auto_clicker:
        type: boolean
      updated_at:
        type: integer
      created_at:
        type: integer

  CardUpdateBody:
    type: object
    properties:
      card_name:
        type: string
        enum:
        - power_click
        - auto_clicker
        - energy_booster

  TapTokenBody:
    type: object
    required:
      - tap_token
    properties:
      tap_token:
        type: string