swagger: '2.0'

info:
  title: maxon back
  version: development
  description: Makson zon zon

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

consumes:
  - application/json

produces:
  - application/json

paths:

  /save_progress:
    post:
      summary: Save Progress
      operationId: SaveProgress
      tags: 
        - Progress
      parameters:
        - name: Progress
          description: Save progress body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Progress'
      responses:
        200:
          description: Save Progress Response
          schema:
            $ref: '#/definitions/Error'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error' 
        422:
          description: Unprocessable Entity
          schema:
            $ref: "#/definitions/Error"        
        500:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'

definitions:

  Progress:
    type: object
    required:
      - coin_number
      - click_booster
      - auto_clicker
    properties:
      tg_id:
        type: integer
      coin_number:
        type: integer
      click_booster:
        type: integer
      auto_clicker:
        type: boolean

  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string