swagger: '2.0'

info:
  title: maxon back
  version: development
  description: Makson zon zon

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

consumes:
  - application/json

produces:
  - application/json