// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetNearBody get near body
//
// swagger:model GetNearBody
type GetNearBody struct {

	// amount
	Amount float64 `json:"amount,omitempty"`

	// receiving wallet
	ReceivingWallet string `json:"receiving_wallet,omitempty"`

	// token contract
	TokenContract string `json:"token_contract,omitempty"`
}

// Validate validates this get near body
func (m *GetNearBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get near body based on context it is used
func (m *GetNearBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetNearBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetNearBody) UnmarshalBinary(b []byte) error {
	var res GetNearBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
