// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NearTransit near transit
//
// swagger:model NearTransit
type NearTransit struct {

	// result
	Result string `json:"result,omitempty"`
}

// Validate validates this near transit
func (m *NearTransit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this near transit based on context it is used
func (m *NearTransit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NearTransit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NearTransit) UnmarshalBinary(b []byte) error {
	var res NearTransit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
