// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ReferralLink referral link
//
// swagger:model ReferralLink
type ReferralLink struct {

	// referral link
	// Required: true
	ReferralLink *string `json:"referral_link"`
}

// Validate validates this referral link
func (m *ReferralLink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReferralLink(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReferralLink) validateReferralLink(formats strfmt.Registry) error {

	if err := validate.Required("referral_link", "body", m.ReferralLink); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this referral link based on context it is used
func (m *ReferralLink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReferralLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReferralLink) UnmarshalBinary(b []byte) error {
	var res ReferralLink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
