// Code generated by go-swagger; DO NOT EDIT.

package definition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// StartEnergyCollectBody start energy collect body
//
// swagger:model StartEnergyCollectBody
type StartEnergyCollectBody struct {

	// current energy token
	// Required: true
	CurrentEnergyToken *string `json:"current_energy_token"`
}

// Validate validates this start energy collect body
func (m *StartEnergyCollectBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrentEnergyToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StartEnergyCollectBody) validateCurrentEnergyToken(formats strfmt.Registry) error {

	if err := validate.Required("current_energy_token", "body", m.CurrentEnergyToken); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this start energy collect body based on context it is used
func (m *StartEnergyCollectBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StartEnergyCollectBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StartEnergyCollectBody) UnmarshalBinary(b []byte) error {
	var res StartEnergyCollectBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
